### PR TITLE
Automatic retries on failure

### PR DESCRIPTION
**Pull request by milesmcc**
This small PR adds automatic retries (up to three times) on failure in `_paged_request`. Often, when I'm scraping a popular tag, I run into an error after about two minutes of scraping (around 25-50 pages). An immediate retry usually works; automatic retries seem like a great way to improve the robustness of the tool (and avoid having to restart searches from scratch).

I'm happy to implement the retry logic differently/elsewhere if you prefer. I'm also happy to make the retry amount configurable (right now it's fixed at 3) if you think that would be valuable.

### CODE REVIEW

**Comment by castle-lemongrab** [comment]
Thanks, I'll review this ASAP. I can see a couple of _very_ minor potential changes from a quick scan, but this is definitely useful and it'll get merged. Apologies in advance for the delay; I'm expecting somewhere between 24 and 48 hours.

**Comment by milesmcc** [comment]
For sure -- let me know what you need. And I can also revert the accidental changes to `package-lock.json` (just updates) and the typo fix in `SECURITY.md` if you want to keep the scope of the PR narrow.

**Comment by castle-lemongrab** [comment]
Merged.

The only things I might change in the near future are (i) the wording of the log message, (ii) to pull the retry limit up to a class-level variable that defaults to three but can be overridden via `_options` and (maybe) a CLI option, and (iii) potentially invoke the ratelimiter for each retry. The `package-lock.json` file will get updated anyway before release anyway.

I'll link any relevant commits for changes I make here, but IMO they're not worth holding up a merge over. I've been meaning to add that `try` for a while, as I've also seen Parler bounce requests with an HTTP 429 despite being within the ratelimit parameters. This works and gets proper error handling started.

If you want to grab any of the items above before I get to them, feel free. Parler's definitely a moving target, so my inclination is to merge early and often, rather than hold up PRs that provide functionality over minor-to-trivial improvements.

Thanks for the PR!

**Comment by milesmcc** [comment]
Perfect! Thanks for the merge — this will be very helpful. And I see that you already implemented most of the changes you described. Sorry I didn’t get to them first! I’m excited to continue helping out here. Miles

**Comment by castle-lemongrab** [comment]
No worries at all; thanks for the help. A lot of this stuff is technically straightforward, but certain items you'd expect to see (e.g. decent unit testing) were put off temporarily because we overestimated Parler's ability to make rapid changes to their APIs. Feel free to grab anything that looks interesting; I've granted permissions that should be sufficient for you to self-assign issues and/or create working branches in this repository.

**Pull request merged**
